name: 'GraphQL Diff'
description: 'A neat summary of the changes you made to your GraphQL schema.'
branding: 
  icon: 'book-open'
  color: 'purple'
inputs:
  token:
    description: 'GitHub token to post the comment'
    required: true
  old-schema: 
    description: 'Old schema location'
    required: true
  new-schema:
    description: 'New schema location'
    required: true
  header:
    description: 'Header to use in the comment'
    required: false
    default: '## 🗞 GraphQL Summary'
  fail-on-diff:
    description: 'Produces an error if there is a diff'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'